// SPDX-License-Identifier: AGPL-3.0-only
import { index, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { users } from './users.js';

/**
 * App installations of a user, for push delivery (Plan v7 §11, PUT /v1/devices/{installationId}).
 * Rows go away with the user (ON DELETE CASCADE).
 */
export const devices = pgTable(
  'devices',
  {
    /** Random id generated by the app on first launch; stable per installation. */
    installationId: text('installation_id').primaryKey(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** PERSONAL DATA: Firebase Cloud Messaging token that can reach this device. */
    fcmToken: text('fcm_token'),
    appVersion: text('app_version'),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('devices_user_id_idx').on(t.userId)],
);
