-- SPDX-License-Identifier: AGPL-3.0-only
-- Generated by drizzle-kit from src/db/schema; COMMENT statements at the end were added by hand
-- (drizzle cannot express them). Expand-only: creates new objects, changes nothing existing.
CREATE TABLE "audit_log" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"actor_user_id" uuid,
	"actor_type" text NOT NULL,
	"action" text NOT NULL,
	"entity" text NOT NULL,
	"entity_id" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "audit_log_actor_type_check" CHECK ("audit_log"."actor_type" in ('user', 'moderator', 'admin', 'system'))
);
--> statement-breakpoint
CREATE TABLE "devices" (
	"installation_id" text PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"fcm_token" text,
	"app_version" text,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "idempotency_keys" (
	"user_id" uuid NOT NULL,
	"key" text NOT NULL,
	"route" text NOT NULL,
	"response_hash" text NOT NULL,
	"response_status" smallint NOT NULL,
	"response_body" jsonb,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "idempotency_keys_pkey" PRIMARY KEY("user_id","route","key")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"firebase_uid" text NOT NULL,
	"phone_e164" text,
	"display_name" text,
	"locale" text DEFAULT 'en' NOT NULL,
	"role" text DEFAULT 'user' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "users_firebase_uid_unique" UNIQUE("firebase_uid"),
	CONSTRAINT "users_locale_check" CHECK ("users"."locale" in ('en', 'bn')),
	CONSTRAINT "users_role_check" CHECK ("users"."role" in ('user', 'moderator', 'admin'))
);
--> statement-breakpoint
ALTER TABLE "devices" ADD CONSTRAINT "devices_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idempotency_keys" ADD CONSTRAINT "idempotency_keys_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_log_entity_idx" ON "audit_log" USING btree ("entity","entity_id");--> statement-breakpoint
CREATE INDEX "audit_log_at_idx" ON "audit_log" USING btree ("at");--> statement-breakpoint
CREATE INDEX "devices_user_id_idx" ON "devices" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idempotency_keys_expires_at_idx" ON "idempotency_keys" USING btree ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "users_phone_e164_key" ON "users" USING btree ("phone_e164") WHERE "users"."phone_e164" is not null;--> statement-breakpoint
COMMENT ON TABLE "audit_log" IS 'Append-only audit trail. metadata must never contain precise locations, tokens, phone numbers or message text (Plan v7 §11, §12.2). actor_user_id has no FK so rows survive account deletion.';--> statement-breakpoint
COMMENT ON COLUMN "users"."firebase_uid" IS 'PERSONAL DATA: Firebase Auth user id (export/erasure P020).';--> statement-breakpoint
COMMENT ON COLUMN "users"."phone_e164" IS 'PERSONAL DATA: verified phone number, E.164 (export/erasure P020).';--> statement-breakpoint
COMMENT ON COLUMN "users"."display_name" IS 'PERSONAL DATA: display name (export/erasure P020).';--> statement-breakpoint
COMMENT ON COLUMN "devices"."fcm_token" IS 'PERSONAL DATA: FCM push token (export/erasure P020).';
