-- SPDX-License-Identifier: AGPL-3.0-only
-- Generated by drizzle-kit from src/db/schema; COMMENT statements at the end were added by hand
-- (drizzle cannot express them). Expand-only: one new table and one nullable column (ADR 0003, ADR 0010).
CREATE TABLE "consent_records" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"purpose" text NOT NULL,
	"status" text NOT NULL,
	"notice_version" text NOT NULL,
	"notice_locale" text NOT NULL,
	"decided_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "consent_records_purpose_check" CHECK ("consent_records"."purpose" ~ '^[a-z][a-z0-9_]{2,40}$'),
	CONSTRAINT "consent_records_status_check" CHECK ("consent_records"."status" in ('granted', 'withdrawn')),
	CONSTRAINT "consent_records_notice_locale_check" CHECK ("consent_records"."notice_locale" in ('en', 'bn'))
);
--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "adult_attested_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "consent_records" ADD CONSTRAINT "consent_records_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "consent_records_user_purpose_decided_idx" ON "consent_records" USING btree ("user_id","purpose","decided_at" DESC NULLS FIRST);--> statement-breakpoint
COMMENT ON TABLE "consent_records" IS 'PERSONAL DATA: append-only history of a user''s consent decisions per purpose (ADR 0010). Rows are never updated; the newest row per purpose is the current state. Export/erasure and retention: P020.';--> statement-breakpoint
COMMENT ON COLUMN "users"."adult_attested_at" IS 'PERSONAL DATA: when the user declared being 18 or older; no date of birth is collected (export/erasure P020).';
