-- SPDX-License-Identifier: AGPL-3.0-only
-- Generated by drizzle-kit from src/db/schema; the COMMENT statement at the end was added by hand
-- (drizzle cannot express it). Expand-only: one new table (ADR 0003, ADR 0018).
CREATE TABLE "rate_limit_buckets" (
	"key" text PRIMARY KEY NOT NULL,
	"user_id" uuid,
	"tokens" double precision NOT NULL,
	"refilled_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "rate_limit_buckets" ADD CONSTRAINT "rate_limit_buckets_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "rate_limit_buckets_user_id_idx" ON "rate_limit_buckets" USING btree ("user_id");--> statement-breakpoint
COMMENT ON TABLE "rate_limit_buckets" IS 'Token buckets for rate limits, one row per bucket, updated in place (ADR 0018). No personal data except user_id: the key never holds a query, a location, a phone number or an IP address. Stale rows are purged in P020.';
