-- SPDX-License-Identifier: AGPL-3.0-only
-- Generated by drizzle-kit from src/db/schema; COMMENT statements at the end were added by hand
-- (drizzle cannot express them). Expand-only: two new tables (ADR 0003, ADR 0024).
CREATE TABLE "contact_optout_tokens" (
	"token_hash" "bytea" PRIMARY KEY NOT NULL,
	"contact_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "emergency_contacts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"name" text NOT NULL,
	"phone_e164" text NOT NULL,
	"has_app_user_id" uuid,
	"invited_at" timestamp with time zone,
	"opted_out_at" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "emergency_contacts_user_phone_key" UNIQUE("user_id","phone_e164"),
	CONSTRAINT "emergency_contacts_name_check" CHECK (char_length("emergency_contacts"."name") between 1 and 80),
	CONSTRAINT "emergency_contacts_phone_e164_check" CHECK ("emergency_contacts"."phone_e164" ~ '^\+[1-9][0-9]{6,14}$')
);
--> statement-breakpoint
ALTER TABLE "contact_optout_tokens" ADD CONSTRAINT "contact_optout_tokens_contact_id_emergency_contacts_id_fk" FOREIGN KEY ("contact_id") REFERENCES "public"."emergency_contacts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "emergency_contacts" ADD CONSTRAINT "emergency_contacts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "emergency_contacts" ADD CONSTRAINT "emergency_contacts_has_app_user_id_users_id_fk" FOREIGN KEY ("has_app_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "contact_optout_tokens_contact_id_idx" ON "contact_optout_tokens" USING btree ("contact_id");--> statement-breakpoint
COMMENT ON TABLE "emergency_contacts" IS 'Emergency contacts of a user (ADR 0024). PERSONAL DATA of people who are not users: name and phone_e164. Export and erasure in P020; rows go away with the account. A row with opted_out_at must never be alerted; with deleted_at as well it is a tombstone that blocks adding the number again.';--> statement-breakpoint
COMMENT ON COLUMN "emergency_contacts"."name" IS 'PERSONAL DATA: the name the user gave this contact. Never in logs or audit metadata.';--> statement-breakpoint
COMMENT ON COLUMN "emergency_contacts"."phone_e164" IS 'PERSONAL DATA: the phone number of the contact in E.164 form. Never in logs or audit metadata.';--> statement-breakpoint
COMMENT ON TABLE "contact_optout_tokens" IS 'SHA-256 hashes of opt-out link tokens (ADR 0024). The plaintext token is never stored.';
